In [3]:
import random
import numpy as np
np.random.seed(6)
X = np.random.randint(10, 100, 100)
X = X.reshape(20,5)
print(X)

[[20 83 94 89 90]
 [72 35 11 85 87]
 [67 36 43 78 43]
 [18 12 86 94 41]
 [76 15 36 25 99]
 [96 53 79 59 14]
 [72 90 76 76 73]
 [29 95 38 53 67]
 [15 60 36 88 50]
 [79 80 73 20 77]
 [95 21 11 92 45]
 [32 51 34 58 52]
 [77 17 46 85 66]
 [43 86 78 43 25]
 [79 57 31 80 11]
 [19 58 52 50 87]
 [83 75 73 92 76]
 [35 31 86 78 39]
 [24 32 13 43 46]
 [34 70 88 84 68]]


In [4]:
# B1 : De-Mean (Chuẩn hóa dữ liệu)
X_mean = X - np.mean(X, axis = 0)
print(X_mean)

[[-33.25  30.15  39.8   20.4   32.2 ]
 [ 18.75 -17.85 -43.2   16.4   29.2 ]
 [ 13.75 -16.85 -11.2    9.4  -14.8 ]
 [-35.25 -40.85  31.8   25.4  -16.8 ]
 [ 22.75 -37.85 -18.2  -43.6   41.2 ]
 [ 42.75   0.15  24.8   -9.6  -43.8 ]
 [ 18.75  37.15  21.8    7.4   15.2 ]
 [-24.25  42.15 -16.2  -15.6    9.2 ]
 [-38.25   7.15 -18.2   19.4   -7.8 ]
 [ 25.75  27.15  18.8  -48.6   19.2 ]
 [ 41.75 -31.85 -43.2   23.4  -12.8 ]
 [-21.25  -1.85 -20.2  -10.6   -5.8 ]
 [ 23.75 -35.85  -8.2   16.4    8.2 ]
 [-10.25  33.15  23.8  -25.6  -32.8 ]
 [ 25.75   4.15 -23.2   11.4  -46.8 ]
 [-34.25   5.15  -2.2  -18.6   29.2 ]
 [ 29.75  22.15  18.8   23.4   18.2 ]
 [-18.25 -21.85  31.8    9.4  -18.8 ]
 [-29.25 -20.85 -41.2  -25.6  -11.8 ]
 [-19.25  17.15  33.8   15.4   10.2 ]]


In [5]:
# B2 : Calculate Covariance Matrix (Tính ma trận hiệp phương sai)
Cov = np.cov(X_mean.T)
print(Cov.shape)
print(Cov)


(5, 5)
[[ 812.82894737 -110.38157895 -135.89473684  -13.36842105  -66.68421053]
 [-110.38157895  721.08157895  295.24210526  -99.37894737   77.12631579]
 [-135.89473684  295.24210526  769.01052632   55.71578947   -4.22105263]
 [ -13.36842105  -99.37894737   55.71578947  528.25263158  -81.76842105]
 [ -66.68421053   77.12631579   -4.22105263  -81.76842105  634.90526316]]


In [6]:
# B3 : Find Eigen Values and Eigen Vector (Tính vector riêng và giá trị riêng)
eigen_value, eigen_vector = np.linalg.eigh(Cov)
print(eigen_value)
print(eigen_vector)

[ 370.42936505  507.09646886  709.34986643  730.9234237  1148.27982332]
[[ 0.00528442 -0.20533128 -0.42905365  0.73846136 -0.47791101]
 [ 0.61838356  0.27682671 -0.34919661  0.25477826  0.59507857]
 [-0.53660504 -0.30342174  0.19408637  0.43706681  0.62553447]
 [ 0.57404455 -0.59159474  0.55111296  0.11976086 -0.04919716]
 [-0.01008629 -0.66268918 -0.5937842  -0.42940983  0.15417144]]


In [10]:
# B4 : Select Best Eigen Values and Eigen Vectors for Dimensionality Reduction
# (Sắp xếp giá trị riêng và vector riêng theo thứ tự ưu tiên giảm dần)
# Bộ vector mới còn gọi là "Feature vectors"
n_selectDim = 3
sorted_index = np.flip(np.argsort(eigen_value)) # 4 3 2 1 0
selected_eigenvectors = eigen_vector.T[sorted_index[:n_selectDim]]
print(selected_eigenvectors)

[[-0.47791101  0.59507857  0.62553447 -0.04919716  0.15417144]
 [ 0.73846136  0.25477826  0.43706681  0.11976086 -0.42940983]
 [-0.42905365 -0.34919661  0.19408637  0.55111296 -0.5937842 ]]


In [11]:
# B5 : Project data onto Selected Eigen Vectors to reduce dimesionality
X_mean_projected = np.dot(selected_eigenvectors, X_mean.T).T
print("The data after projected onto eigen vectors : Dimensionality reduction")
print(X_mean_projected)

The data after projected onto eigen vectors : Dimensionality reduction
[[ 62.68913012 -10.86089145   3.58524676]
 [-42.9111001  -20.15761672 -18.49637383]
 [-26.34852694   8.44669922  11.77917583]
 [  8.58971137 -12.28371932  59.53461303]
 [-36.2840672  -23.71123587 -48.56868506]
 [-11.10859554  60.10514293   7.13598255]
 [ 28.76233583  27.19842028 -21.73361106]
 [ 28.72409835 -20.06810624 -21.51846208]
 [  8.9932185  -28.70634085  25.70528266]
 [ 20.96129623  20.08441926 -55.06474224]
 [-69.05373396  12.1336377    5.32087194]
 [ -3.95378712 -23.77128124   3.44501011]
 [-37.35596343   3.2636261    4.90638808]
 [ 35.71578671  22.29762506   2.80881798]
 [-32.12510307  31.39441362  17.07168718]
 [ 23.4738041  -39.70805942 -15.11946478]
 [ 12.37789257  30.81656507 -14.76105643]
 [ 12.25052872   4.05355664  37.97572644]
 [-24.76028698 -42.91811599   4.73237191]
 [ 41.36336184   2.39126123  11.26122099]]


In [9]:
a = np.array([1,6,9,8,5])
print(a)
a_sort = np.sort(a)
print(a_sort)
a_arsort = np.argsort(a)
print(a_arsort)

[1 6 9 8 5]
[1 5 6 8 9]
[0 4 1 3 2]
